sudo: required

dist: xenial

language:
  - c++

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - llvm-toolchain-xenial-8
    packages:
      - clang-format-8
      - clang-8
      - ninja-build
env:
  - CXX=clang++

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.26.0/bazel_0.26.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.26.0-linux-x86_64.deb

jobs:
  include:
    - stage: "Format"
      name: "clang format checker"
      script: bash format.sh
    - stage: "Build"
      name: "library build"
      script: bazel build //sentinel-core/... && bazel build //sentinel-datasource-extension/...
    - stage: "Test"
      name: "sentinel core unit tests"
      script: bazel test --test_output=errors --strategy=TestRunner=standalone //sentinel-core/...
    - script: bazel test --test_output=errors --strategy=TestRunner=standalone //sentinel-datasource-extension/...
      name: "sentinel datasource extension tests"
    - stage: "tsan-flow"
      name: "tsan for flow control"
      script: bazel build -c dbg --config=clang-tsan //tests/... && ./bazel-bin/tests/tsan-flow
